
#define CRT_ROOT "-----BEGIN CERTIFICATE-----" \
"MIICHTCCAc+gAwIBAgIUQZj6nZbs5zXscFU3kpO64QXuo4owBQYDK2VwMHwxCzAJ" \
"BgNVBAYTAlVTMRAwDgYDVQQIDAdGbG9yaWRhMQ4wDAYDVQQHDAVNaWFtaTEMMAoG" \
"A1UECgwDRkFVMQ8wDQYDVQQLDAZGQVUgQ0ExDzANBgNVBAMMBkZBVSBDQTEbMBkG" \
"CSqGSIb3DQEJARYMaW5mb0BmYXUuZWR1MB4XDTI0MDIwNTE2NTYwOFoXDTI2MTEy" \
"NTE2NTYwOFowfDELMAkGA1UEBhMCVVMxEDAOBgNVBAgMB0Zsb3JpZGExDjAMBgNV" \
"BAcMBU1pYW1pMQwwCgYDVQQKDANGQVUxDzANBgNVBAsMBkZBVSBDQTEPMA0GA1UE" \
"AwwGRkFVIENBMRswGQYJKoZIhvcNAQkBFgxpbmZvQGZhdS5lZHUwKjAFBgMrZXAD" \
"IQBIDdR0vr8rArUoCtqv6OYgQO36g4DKC061cdzUs9q+pKNjMGEwHQYDVR0OBBYE" \
"FE0IwXE3wyJ5kTKmz9vgnDbgxdqPMB8GA1UdIwQYMBaAFE0IwXE3wyJ5kTKmz9vg" \
"nDbgxdqPMA8GA1UdEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgGGMAUGAytlcANB" \
"AGYW0VqPZM02a/Hkj2jeW7wP3Hv+l1OZJ0AJgdBsFzd08k0Na8Cb1s3dB1JE+87Y" \
"ZmapRDfGG/qxMHEWpmHjGgQ=" \
"-----END CERTIFICATE-----" 
#define KEY_CMP1 "-----BEGIN PRIVATE KEY-----" \
"MC4CAQAwBQYDK2VwBCIEIG6DGSY3vZ/J2UhI8DNT/UEve9CRlJsbOpv55Oca/IHt" \
"-----END PRIVATE KEY-----" 
#define CRT_CMP1 "-----BEGIN CERTIFICATE-----" \
"MIIBszCCAWUCFCZsWfElScp5nF9NFzTyfghIr9ZSMAUGAytlcDB8MQswCQYDVQQG" \
"EwJVUzEQMA4GA1UECAwHRmxvcmlkYTEOMAwGA1UEBwwFTWlhbWkxDDAKBgNVBAoM" \
"A0ZBVTEPMA0GA1UECwwGRkFVIENBMQ8wDQYDVQQDDAZGQVUgQ0ExGzAZBgkqhkiG" \
"9w0BCQEWDGluZm9AZmF1LmVkdTAeFw0yNDAyMDUxNjU2MDhaFw0yNTAyMDQxNjU2" \
"MDhaMHwxCzAJBgNVBAYTAlVTMRAwDgYDVQQIDAdGbG9yaWRhMQ4wDAYDVQQHDAVN" \
"aWFtaTEMMAoGA1UECgwDRkFVMQ8wDQYDVQQLDAZGQVUgQ0ExDzANBgNVBAMMBkZB" \
"VSBDQTEbMBkGCSqGSIb3DQEJARYMaW5mb0BmYXUuZWR1MCowBQYDK2VwAyEAMAtp" \
"1GnutnEXZ1Ik3h+sFmi6x6qGbJCfI0K1y8Hz4NIwBQYDK2VwA0EA3ke/StUeX5uf" \
"Rc2ISu+9BPoWn8nvdk3VgV+/6sq7OjNEKvOj7UQ9G3kjximwO2nmRST4cMe9gUQ5" \
"40NO/yznCQ==" \
"-----END CERTIFICATE-----" 
#define CRT_AP "-----BEGIN CERTIFICATE-----" \
"MIIBszCCAWUCFCZsWfElScp5nF9NFzTyfghIr9ZRMAUGAytlcDB8MQswCQYDVQQG" \
"EwJVUzEQMA4GA1UECAwHRmxvcmlkYTEOMAwGA1UEBwwFTWlhbWkxDDAKBgNVBAoM" \
"A0ZBVTEPMA0GA1UECwwGRkFVIENBMQ8wDQYDVQQDDAZGQVUgQ0ExGzAZBgkqhkiG" \
"9w0BCQEWDGluZm9AZmF1LmVkdTAeFw0yNDAyMDUxNjU2MDhaFw0yNTAyMDQxNjU2" \
"MDhaMHwxCzAJBgNVBAYTAlVTMRAwDgYDVQQIDAdGbG9yaWRhMQ4wDAYDVQQHDAVN" \
"aWFtaTEMMAoGA1UECgwDRkFVMQ8wDQYDVQQLDAZGQVUgQ0ExDzANBgNVBAMMBkZB" \
"VSBDQTEbMBkGCSqGSIb3DQEJARYMaW5mb0BmYXUuZWR1MCowBQYDK2VwAyEAbNWb" \
"YkbgiV1kaws5lUG+aQmtYcB+XOWpY87YAVeEe28wBQYDK2VwA0EA8WEr2xijJvAj" \
"l7sr0OMUkZWrq2XLwqsZJGlnH6DGBxMWupy3r/CGwI3xYiXuJ50XpiqQoBNLcekY" \
"THWeE4EsBg==" \
"-----END CERTIFICATE-----" 