
#define PEM_ROOTCA "-----BEGIN CERTIFICATE-----" \
"MIICHTCCAc+gAwIBAgIUK+pstfMpRltBhUUxrTHljoUNV7kwBQYDK2VwMHwxCzAJ" \
"BgNVBAYTAlVTMRAwDgYDVQQIDAdGbG9yaWRhMQ4wDAYDVQQHDAVNaWFtaTEMMAoG" \
"A1UECgwDRkFVMQ8wDQYDVQQLDAZGQVUgQ0ExDzANBgNVBAMMBkZBVSBDQTEbMBkG" \
"CSqGSIb3DQEJARYMaW5mb0BmYXUuZWR1MB4XDTI0MDIwNTA0MjM1OVoXDTI2MTEy" \
"NTA0MjM1OVowfDELMAkGA1UEBhMCVVMxEDAOBgNVBAgMB0Zsb3JpZGExDjAMBgNV" \
"BAcMBU1pYW1pMQwwCgYDVQQKDANGQVUxDzANBgNVBAsMBkZBVSBDQTEPMA0GA1UE" \
"AwwGRkFVIENBMRswGQYJKoZIhvcNAQkBFgxpbmZvQGZhdS5lZHUwKjAFBgMrZXAD" \
"IQAY+FuNyZyP1XkopoSDTe8Cw6uJqA6XC8tinbYGo8fhb6NjMGEwHQYDVR0OBBYE" \
"FFtXjUQYHK+apNgmOuNiVpisO9/kMB8GA1UdIwQYMBaAFFtXjUQYHK+apNgmOuNi" \
"VpisO9/kMA8GA1UdEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgGGMAUGAytlcANB" \
"ADHlq7D2Ab8ij0UStjFXIQALoJXm5tyzO3btEFva8a77fKGDEWtgh6cGUTAmH8pI" \
"9sZxIErny1ypMB68oKcb9gs=" \
"-----END CERTIFICATE-----" 
#define KEY_AP "-----BEGIN PRIVATE KEY-----" \
"MC4CAQAwBQYDK2VwBCIEIG9hyGf12DXu8Ji5/ChkVEuuJb7JeSCbmPd5zbTQterJ" \
"-----END PRIVATE KEY-----" 
#define KEY_AP "-----BEGIN CERTIFICATE-----" \
"MIIBszCCAWUCFA3771ZkaVJRF5B368au3hq4RXm/MAUGAytlcDB8MQswCQYDVQQG" \
"EwJVUzEQMA4GA1UECAwHRmxvcmlkYTEOMAwGA1UEBwwFTWlhbWkxDDAKBgNVBAoM" \
"A0ZBVTEPMA0GA1UECwwGRkFVIENBMQ8wDQYDVQQDDAZGQVUgQ0ExGzAZBgkqhkiG" \
"9w0BCQEWDGluZm9AZmF1LmVkdTAeFw0yNDAyMDUwNDIzNTlaFw0yNTAyMDQwNDIz" \
"NTlaMHwxCzAJBgNVBAYTAlVTMRAwDgYDVQQIDAdGbG9yaWRhMQ4wDAYDVQQHDAVN" \
"aWFtaTEMMAoGA1UECgwDRkFVMQ8wDQYDVQQLDAZGQVUgQ0ExDzANBgNVBAMMBkZB" \
"VSBDQTEbMBkGCSqGSIb3DQEJARYMaW5mb0BmYXUuZWR1MCowBQYDK2VwAyEAStC+" \
"I8Q/rOUn+O3lySQhwjQh1YkCz7pKEwZVCLb83hwwBQYDK2VwA0EAum/R/qM8OSzT" \
"LuO9J3GCiyUxPtFXV7HwuRanOndOW5TKuNrqALIASKIondBAlKe9BNl3WOoxIgKD" \
"iVGP9an5CQ==" \
"-----END CERTIFICATE-----" 
#define KEY_CMP2 "-----BEGIN CERTIFICATE-----" \
"MIIBszCCAWUCFA3771ZkaVJRF5B368au3hq4RXnBMAUGAytlcDB8MQswCQYDVQQG" \
"EwJVUzEQMA4GA1UECAwHRmxvcmlkYTEOMAwGA1UEBwwFTWlhbWkxDDAKBgNVBAoM" \
"A0ZBVTEPMA0GA1UECwwGRkFVIENBMQ8wDQYDVQQDDAZGQVUgQ0ExGzAZBgkqhkiG" \
"9w0BCQEWDGluZm9AZmF1LmVkdTAeFw0yNDAyMDUwNDIzNTlaFw0yNTAyMDQwNDIz" \
"NTlaMHwxCzAJBgNVBAYTAlVTMRAwDgYDVQQIDAdGbG9yaWRhMQ4wDAYDVQQHDAVN" \
"aWFtaTEMMAoGA1UECgwDRkFVMQ8wDQYDVQQLDAZGQVUgQ0ExDzANBgNVBAMMBkZB" \
"VSBDQTEbMBkGCSqGSIb3DQEJARYMaW5mb0BmYXUuZWR1MCowBQYDK2VwAyEAdJIy" \
"jrqfL8FI0rHKyN3GiilOgHMK/t6uQ+HhW3dnZVswBQYDK2VwA0EA+Kbxee/sdGLs" \
"xb6qd0ntNEarkrf06sqXnZRDGsydkpeUZvXS4OuAR1JfNCU5jfUrCZkH4wNciMDL" \
"DytFYgcVCQ==" \
"-----END CERTIFICATE-----" 