
#define PEM_ROOTCA "-----BEGIN CERTIFICATE-----" \
"MIICHTCCAc+gAwIBAgIUK+pstfMpRltBhUUxrTHljoUNV7kwBQYDK2VwMHwxCzAJ" \
"BgNVBAYTAlVTMRAwDgYDVQQIDAdGbG9yaWRhMQ4wDAYDVQQHDAVNaWFtaTEMMAoG" \
"A1UECgwDRkFVMQ8wDQYDVQQLDAZGQVUgQ0ExDzANBgNVBAMMBkZBVSBDQTEbMBkG" \
"CSqGSIb3DQEJARYMaW5mb0BmYXUuZWR1MB4XDTI0MDIwNTA0MjM1OVoXDTI2MTEy" \
"NTA0MjM1OVowfDELMAkGA1UEBhMCVVMxEDAOBgNVBAgMB0Zsb3JpZGExDjAMBgNV" \
"BAcMBU1pYW1pMQwwCgYDVQQKDANGQVUxDzANBgNVBAsMBkZBVSBDQTEPMA0GA1UE" \
"AwwGRkFVIENBMRswGQYJKoZIhvcNAQkBFgxpbmZvQGZhdS5lZHUwKjAFBgMrZXAD" \
"IQAY+FuNyZyP1XkopoSDTe8Cw6uJqA6XC8tinbYGo8fhb6NjMGEwHQYDVR0OBBYE" \
"FFtXjUQYHK+apNgmOuNiVpisO9/kMB8GA1UdIwQYMBaAFFtXjUQYHK+apNgmOuNi" \
"VpisO9/kMA8GA1UdEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgGGMAUGAytlcANB" \
"ADHlq7D2Ab8ij0UStjFXIQALoJXm5tyzO3btEFva8a77fKGDEWtgh6cGUTAmH8pI" \
"9sZxIErny1ypMB68oKcb9gs=" \
"-----END CERTIFICATE-----" 
#define KEY_AP "-----BEGIN PRIVATE KEY-----" \
"MC4CAQAwBQYDK2VwBCIEIGXAuTYMtIKkBDvsmZI2IGcTpHDCiAMAOHLKea1K/z6J" \
"-----END PRIVATE KEY-----" 
#define KEY_CMP1 "-----BEGIN CERTIFICATE-----" \
"MIIBszCCAWUCFA3771ZkaVJRF5B368au3hq4RXnAMAUGAytlcDB8MQswCQYDVQQG" \
"EwJVUzEQMA4GA1UECAwHRmxvcmlkYTEOMAwGA1UEBwwFTWlhbWkxDDAKBgNVBAoM" \
"A0ZBVTEPMA0GA1UECwwGRkFVIENBMQ8wDQYDVQQDDAZGQVUgQ0ExGzAZBgkqhkiG" \
"9w0BCQEWDGluZm9AZmF1LmVkdTAeFw0yNDAyMDUwNDIzNTlaFw0yNTAyMDQwNDIz" \
"NTlaMHwxCzAJBgNVBAYTAlVTMRAwDgYDVQQIDAdGbG9yaWRhMQ4wDAYDVQQHDAVN" \
"aWFtaTEMMAoGA1UECgwDRkFVMQ8wDQYDVQQLDAZGQVUgQ0ExDzANBgNVBAMMBkZB" \
"VSBDQTEbMBkGCSqGSIb3DQEJARYMaW5mb0BmYXUuZWR1MCowBQYDK2VwAyEA2mMB" \
"Zz72LJfk6v5mr4h/wJ4fDedDjh5GIpdTXvHc4LAwBQYDK2VwA0EAAdetuJozVMy+" \
"nud2XepBI7ecNzhl6dU/oU0bhfGgdA6OjugkWs44ZAw1rCLdZcc7xZBakfKf1Nue" \
"bcND3WNhDw==" \
"-----END CERTIFICATE-----" 
#define KEY_CMP2 "-----BEGIN CERTIFICATE-----" \
"MIIBszCCAWUCFA3771ZkaVJRF5B368au3hq4RXnBMAUGAytlcDB8MQswCQYDVQQG" \
"EwJVUzEQMA4GA1UECAwHRmxvcmlkYTEOMAwGA1UEBwwFTWlhbWkxDDAKBgNVBAoM" \
"A0ZBVTEPMA0GA1UECwwGRkFVIENBMQ8wDQYDVQQDDAZGQVUgQ0ExGzAZBgkqhkiG" \
"9w0BCQEWDGluZm9AZmF1LmVkdTAeFw0yNDAyMDUwNDIzNTlaFw0yNTAyMDQwNDIz" \
"NTlaMHwxCzAJBgNVBAYTAlVTMRAwDgYDVQQIDAdGbG9yaWRhMQ4wDAYDVQQHDAVN" \
"aWFtaTEMMAoGA1UECgwDRkFVMQ8wDQYDVQQLDAZGQVUgQ0ExDzANBgNVBAMMBkZB" \
"VSBDQTEbMBkGCSqGSIb3DQEJARYMaW5mb0BmYXUuZWR1MCowBQYDK2VwAyEAdJIy" \
"jrqfL8FI0rHKyN3GiilOgHMK/t6uQ+HhW3dnZVswBQYDK2VwA0EA+Kbxee/sdGLs" \
"xb6qd0ntNEarkrf06sqXnZRDGsydkpeUZvXS4OuAR1JfNCU5jfUrCZkH4wNciMDL" \
"DytFYgcVCQ==" \
"-----END CERTIFICATE-----" 