
#define PEM_ROOTCA "-----BEGIN CERTIFICATE-----" \
"MIICHTCCAc+gAwIBAgIUK+pstfMpRltBhUUxrTHljoUNV7kwBQYDK2VwMHwxCzAJ" \
"BgNVBAYTAlVTMRAwDgYDVQQIDAdGbG9yaWRhMQ4wDAYDVQQHDAVNaWFtaTEMMAoG" \
"A1UECgwDRkFVMQ8wDQYDVQQLDAZGQVUgQ0ExDzANBgNVBAMMBkZBVSBDQTEbMBkG" \
"CSqGSIb3DQEJARYMaW5mb0BmYXUuZWR1MB4XDTI0MDIwNTA0MjM1OVoXDTI2MTEy" \
"NTA0MjM1OVowfDELMAkGA1UEBhMCVVMxEDAOBgNVBAgMB0Zsb3JpZGExDjAMBgNV" \
"BAcMBU1pYW1pMQwwCgYDVQQKDANGQVUxDzANBgNVBAsMBkZBVSBDQTEPMA0GA1UE" \
"AwwGRkFVIENBMRswGQYJKoZIhvcNAQkBFgxpbmZvQGZhdS5lZHUwKjAFBgMrZXAD" \
"IQAY+FuNyZyP1XkopoSDTe8Cw6uJqA6XC8tinbYGo8fhb6NjMGEwHQYDVR0OBBYE" \
"FFtXjUQYHK+apNgmOuNiVpisO9/kMB8GA1UdIwQYMBaAFFtXjUQYHK+apNgmOuNi" \
"VpisO9/kMA8GA1UdEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgGGMAUGAytlcANB" \
"ADHlq7D2Ab8ij0UStjFXIQALoJXm5tyzO3btEFva8a77fKGDEWtgh6cGUTAmH8pI" \
"9sZxIErny1ypMB68oKcb9gs=" \
"-----END CERTIFICATE-----" 
#define KEY_AP "-----BEGIN PRIVATE KEY-----" \
"MC4CAQAwBQYDK2VwBCIEIHGtmaS9VRFTtNWDXd2BG93HMGrgow5Ba2zvT6S5GaOu" \
"-----END PRIVATE KEY-----" 
#define KEY_AP "-----BEGIN CERTIFICATE-----" \
"MIIBszCCAWUCFA3771ZkaVJRF5B368au3hq4RXm/MAUGAytlcDB8MQswCQYDVQQG" \
"EwJVUzEQMA4GA1UECAwHRmxvcmlkYTEOMAwGA1UEBwwFTWlhbWkxDDAKBgNVBAoM" \
"A0ZBVTEPMA0GA1UECwwGRkFVIENBMQ8wDQYDVQQDDAZGQVUgQ0ExGzAZBgkqhkiG" \
"9w0BCQEWDGluZm9AZmF1LmVkdTAeFw0yNDAyMDUwNDIzNTlaFw0yNTAyMDQwNDIz" \
"NTlaMHwxCzAJBgNVBAYTAlVTMRAwDgYDVQQIDAdGbG9yaWRhMQ4wDAYDVQQHDAVN" \
"aWFtaTEMMAoGA1UECgwDRkFVMQ8wDQYDVQQLDAZGQVUgQ0ExDzANBgNVBAMMBkZB" \
"VSBDQTEbMBkGCSqGSIb3DQEJARYMaW5mb0BmYXUuZWR1MCowBQYDK2VwAyEAStC+" \
"I8Q/rOUn+O3lySQhwjQh1YkCz7pKEwZVCLb83hwwBQYDK2VwA0EAum/R/qM8OSzT" \
"LuO9J3GCiyUxPtFXV7HwuRanOndOW5TKuNrqALIASKIondBAlKe9BNl3WOoxIgKD" \
"iVGP9an5CQ==" \
"-----END CERTIFICATE-----" 
#define KEY_CMP1 "-----BEGIN CERTIFICATE-----" \
"MIIBszCCAWUCFA3771ZkaVJRF5B368au3hq4RXnAMAUGAytlcDB8MQswCQYDVQQG" \
"EwJVUzEQMA4GA1UECAwHRmxvcmlkYTEOMAwGA1UEBwwFTWlhbWkxDDAKBgNVBAoM" \
"A0ZBVTEPMA0GA1UECwwGRkFVIENBMQ8wDQYDVQQDDAZGQVUgQ0ExGzAZBgkqhkiG" \
"9w0BCQEWDGluZm9AZmF1LmVkdTAeFw0yNDAyMDUwNDIzNTlaFw0yNTAyMDQwNDIz" \
"NTlaMHwxCzAJBgNVBAYTAlVTMRAwDgYDVQQIDAdGbG9yaWRhMQ4wDAYDVQQHDAVN" \
"aWFtaTEMMAoGA1UECgwDRkFVMQ8wDQYDVQQLDAZGQVUgQ0ExDzANBgNVBAMMBkZB" \
"VSBDQTEbMBkGCSqGSIb3DQEJARYMaW5mb0BmYXUuZWR1MCowBQYDK2VwAyEA2mMB" \
"Zz72LJfk6v5mr4h/wJ4fDedDjh5GIpdTXvHc4LAwBQYDK2VwA0EAAdetuJozVMy+" \
"nud2XepBI7ecNzhl6dU/oU0bhfGgdA6OjugkWs44ZAw1rCLdZcc7xZBakfKf1Nue" \
"bcND3WNhDw==" \
"-----END CERTIFICATE-----" 