#ifndef __ECTF_PARAMS__
#define __ECTF_PARAMS__
#define COMPONENT_ID 286331174
#define COMPONENT_BOOT_MSG "Component 3 Boot!"
#define ATTESTATION_LOC "ATST_LOC3"
#define ATTESTATION_DATE "10/10/10"
#define ATTESTATION_CUSTOMER "ATST_CUST3"
#endif
