#ifndef __ECTF_PARAMS__
#define __ECTF_PARAMS__
#define COMPONENT_ID 286331173
#define COMPONENT_BOOT_MSG "Component 2 Boot!"
#define ATTESTATION_LOC "ATST_LOC2"
#define ATTESTATION_DATE "09/09/09"
#define ATTESTATION_CUSTOMER "ATST_CUST2"
#endif
